spring:
  application:
    name: cts
  datasource:
    url: jdbc:h2:file:./data/cts-trading-db
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update  # auto-create / update tables
    show-sql: true      # log SQL in console
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8080

api:
  binance:
    url: https://api.binance.com
  houbi:
    url: https://api.huobi.pro